### PR TITLE
Orbital

### PR DESCRIPTION
**Pull request by jmbarr**
A Class derived from State (OrbitalState) which contains variables and methods to cope with orbiting objects. Also a couple of transition models to calculate simple Keplerian orbits.

### CODE REVIEW

**Comment by jmbarr** [comment]
Not sure how I get CircleCI to find Astropy. ?

**Comment by jmbarr** [comment]
Right, @dcherrie-dstl @nmharwood-dstl, I finally managed to succeed in a rebase. See if you now have what you need. Other interested parties might include @gemmacook and @LJDevlin.

**Comment by dcherrie-dstl** [comment]
Classification: UK OFFICIAL

Much appreciated Jordi,

To help bring Mission Planner components into Stone Soup I started working on a python binding using PyBind11.

To evaluate the approach, I've started with a simpler binding of Mission Planners transform_to() function. If you're interested to see it in action I can provide a quick demo over a jabber screen share. I'm quite impressed with the result, so will move onto extending the binding project to cover Mission Planners sequential processor.

Kind regards,

Daniel

**Comment by sdhiscocks** [comment]
@jmbarr Was this a merge rather than a rebase?

I'd strongly suggest you pause and take stock of the work here, and look to open PRs for each module/feature you've added.

**Comment by jmbarr** [comment]
> @jmbarr Was this a merge rather than a rebase?
> 
A rebase in this instance. (Does it matter?)

> I'd strongly suggest you pause and take stock of the work here, and look to open PRs for each module/feature you've added.
>
That's the plan. Those using this branch had requested some sort of mergebase because they want the functionality of the master on the orbital branch.

Individual PRs to follow...

**Comment by sdhiscocks** [comment]
> > @jmbarr Was this a merge rather than a rebase?
> 
> A rebase in this instance. (Does it matter?)
Just wondering as there are 370+ commits on this PR and not sure how that'd come about with a merge or rebase

**Comment by jmbarr** [comment]
> > > @jmbarr Was this a merge rather than a rebase?
> > 
> > 
> > A rebase in this instance. (Does it matter?)
> 
> Just wondering as there are 370+ commits on this PR and not sure how that'd come about with a merge or rebase\
> 
It did take a while, yes...

**Pull request closed without merging**
