### PR TITLE
Pass States not StateVectors

### PR DESCRIPTION
**Pull request by jmbarr**
Designed to modify the `function()` and `pdf()` methods in `Model` so that they take `State` rather than `StateVector` objects. This so that functions can access parameters not in the state vector.

### CODE REVIEW

**Comment by sdhiscocks** [comment]
There's a few places where we have test models that also need to be updated, as tests are passing where they shouldn't. For example: 
https://github.com/dstl/Stone-Soup/blob/48df0828ac6b43a5a178621f04b07c151315b64f/stonesoup/simulator/tests/conftest.py#L6-L32

**Comment by jmbarr** [comment]
> There's a few places where we have test models that also need to be updated, as tests are passing where they shouldn't. For example:
> 
> https://github.com/dstl/Stone-Soup/blob/48df0828ac6b43a5a178621f04b07c151315b64f/stonesoup/simulator/tests/conftest.py#L6-L32

gah; who's writing bespoke transition models for tests? 

How to track these down?

**Comment by sdhiscocks** [comment]
> How to track these down?

Looks like they are only present in the simulator tests.

**Comment by jmbarr** [comment]
> > How to track these down?
> 
> Looks like they are only present in the simulator tests.

Done those. Any more?

**Pull request closed without merging**
