### PR TITLE
AESA Radar and Beam Shape beam power method argument changes

### PR DESCRIPTION
**Pull request by sdhiscocks**
- Fixes for some default arguments with radar sensors
- Change Radar `BeamShape` so `beam_width` is argument to `beam_power` method
- Add class constant for full width half maximum for `Beam2DGaussian`

### CODE REVIEW

**Comment by apiszcz** [comment]
Possible type issue:

```
    for time, ctracks in self.tracker:
  File "TEST\lib\lib\site-packages\stonesoup\buffered_generator.py", line 44, in __iter__
    for data in method():
  File "TEST\lib\lib\site-packages\stonesoup\tracker\simple.py", line 52, in tracks_gen
    for time, detections in self.detector:
  File "TEST\lib\lib\site-packages\stonesoup\buffered_generator.py", line 44, in __iter__
    for data in method():
  File "TEST\lib\lib\site-packages\stonesoup\simulator\platform.py", line 31, in detections_gen
    detections = sensor.measure(truths_to_be_measured)
  File "TEST\lib\lib\site-packages\stonesoup\sensor\radar\radar.py", line 682, in measure
    det_prob = self.gen_probability(truth)[0]
  File "TEST\lib\lib\site-packages\stonesoup\sensor\radar\radar.py", line 646, in gen_probability
    snr = self._snr_constant * rcs * spoiled_gain ** 2 * directed_power / (r ** 4)
**TypeError: unsupported operand type(s) for *: 'float' and 'NoneType'**
```

**Comment by sdhiscocks** [comment]
> Possible type issue:
> 
> ```
>     for time, ctracks in self.tracker:
>   File "TEST\lib\lib\site-packages\stonesoup\buffered_generator.py", line 44, in __iter__
>     for data in method():
>   File "TEST\lib\lib\site-packages\stonesoup\tracker\simple.py", line 52, in tracks_gen
>     for time, detections in self.detector:
>   File "TEST\lib\lib\site-packages\stonesoup\buffered_generator.py", line 44, in __iter__
>     for data in method():
>   File "TEST\lib\lib\site-packages\stonesoup\simulator\platform.py", line 31, in detections_gen
>     detections = sensor.measure(truths_to_be_measured)
>   File "TEST\lib\lib\site-packages\stonesoup\sensor\radar\radar.py", line 682, in measure
>     det_prob = self.gen_probability(truth)[0]
>   File "TEST\lib\lib\site-packages\stonesoup\sensor\radar\radar.py", line 646, in gen_probability
>     snr = self._snr_constant * rcs * spoiled_gain ** 2 * directed_power / (r ** 4)
> **TypeError: unsupported operand type(s) for *: 'float' and 'NoneType'**
> ```

This is due to not providing a `rcs` value. If added f56dce2 to make error message clearer.

**Comment by apiszcz** [comment]
I'm still learning, past document had optional.
rcs (float, optional) – The radar cross section of targets in meters squared.

**Comment by sdhiscocks** [comment]
> I'm still learning, past document had optional.
> rcs (float, optional) – The radar cross section of targets in meters squared.

Yes, the documentation wasn't clear before. I've also [updated that with new commit](https://github.com/dstl/Stone-Soup/commit/f56dce2a29c45be5c75926282e6cb80216503190#diff-fd4c6dc080e59b87097234befa8164839a1b1b88ce5a74b87d2461ffd790f8b4R551-R552).

**Comment by etfrogers-dstl** [comment]
The changes look sensible, but can I ask what prompted them (and the "bug" label)?

Is the old version broken, or just less logical? Mostly out of interest, but also in case it changes the way this works in some other branches.

**Comment by sdhiscocks** [comment]
> The changes look sensible, but can I ask what prompted them (and the "bug" label)?
> 
@apiszcz raised some queries in Gitter. Granted some changes aren't bugs, but seems the most appropriate category vs. enhancements for release notes (for tool that auto generates our changelog from PRs).

> Is the old version broken, or just less logical? Mostly out of interest, but also in case it changes the way this works in some other branches.

Shouldn't cause any issues if you code is already running: measurement model being optional and removing unessecary `__init__` method 9ccaa1a; and then confusing errors with lack of RCS f56dce2. 

The change to `BeamSweep.beam_power` 5056525 is a breaking change, as seemed odd to have as an optional argument for initialisation, but is only every set just before use inside a function.

**Review by etfrogers-dstl — APPROVED** [review]

**Review by jjosborne-dstl — APPROVED** [review]

**Pull request merged**
