### PR TITLE
Add Pytube to dependencies

### PR DESCRIPTION
**Pull request by etfrogers-dstl**
@sdhiscocks ~I think this also needs adding to setup.py?~

Does this need to go anywhere else?

### CODE REVIEW

**Comment by sdhiscocks** [comment]
The video example requires a fair amount of computing power, and also not really suitable for CircleCI and Read The Docs to be executing due to this, as well as requiring 500MB of model weights being downloaded every time. So decision was made in #251 to add it as a pre-computed example. Therefore, it's not required to build the documentation.

However, there is an issue on Windows and Mac at the moment due to sphinx-gallery checksum's being platform dependent. This should be solved if/when https://github.com/sphinx-gallery/sphinx-gallery/pull/722 is merged.

**Comment by etfrogers-dstl** [comment]
Oops. OK. Thanks for explaining. As I think you know, it still causes my Sphinx build to fail.

**Comment by sdhiscocks** [comment]
@etfrogers-dstl  Work around for now is to restore any modified files in `docs/auto_demos/` and run the following if your using Git Bash on Windows:

```bash
echo -n $(cat docs/demos/Video_Processing.py | md5sum | cut -d\  -f1) > docs/source/auto_demos/Video_Processing.py.md5
```

**Comment by etfrogers-dstl** [comment]
Works. Thanks Steve!

**Pull request closed without merging**
