### PR TITLE
Change Property to use type hints and drop Python 3.5 support

### PR DESCRIPTION
**Pull request by sdhiscocks**
This overall doesn't change behaviour of the code or how Properties on classes are defined, but enabled type hints to be used instead. At the moment, this change is backwards compatible.

This is useful to aid IDE's, using more familiar syntax for typing, and possibly allow future use for type checking.

### CODE REVIEW

**Comment by sdhiscocks** [comment]
This requires minimum of Python 3.6. As Python 3.5 is supported until September 2020, we should ideally still support it for now.

**Comment by sdhiscocks** [comment]
> Looks neat. My only worry would be that this will add more overheads to `BaseMeta`, which already seems to be somewhat costly .

As it's only in the meta class, this just affects during class definition, not when creating instances of classes.

**Review by etfrogers-dstl — APPROVED** [review]
Looks good to me. Not sure if we can merge until the 13th?

Please tell you me you managed to automate most of the changes... 😊

**Comment by etfrogers-dstl** [comment]
Does this (or can it) disallow types of the form `[int]`, which is't actually a valid type (it is a list of types).  It should be `List[int]` (or `Sequence[int]` etc).

When you check for types (e.g. when displaying `Property`s in a GUI, the `[int]` form doesn't really work (you can work around it, but it's very hacky, and easier to go back to the source and fix it...)

**Comment by sdhiscocks** [comment]
> Does this (or can it) disallow types of the form `[int]`, which is't actually a valid type (it is a list of types). It should be `List[int]` (or `Sequence[int]` etc).
> 
> When you check for types (e.g. when displaying `Property`s in a GUI, the `[int]` form doesn't really work (you can work around it, but it's very hacky, and easier to go back to the source and fix it...)

So I checked, and it works with bad form as well unfortunately. I thought Python would raise an error as invalid type specification. Hopefully this change has got everything as the right types now, and we'll review types more closely going forward.

**Comment by etfrogers-dstl** [comment]
Should we remove the check `if sys.version_info <= (3, 6)` on line 225 of `base.py` in this PR?

**Comment by sdhiscocks** [comment]
> Should we remove the check `if sys.version_info <= (3, 6)` on line 225 of `base.py` in this PR?

Yeah. In fact there are a few version checks in other places. I'll remove those as well.

**Comment by etfrogers-dstl** [comment]
> > Does this (or can it) disallow types of the form `[int]`, which is't actually a valid type (it is a list of types). It should be `List[int]` (or `Sequence[int]` etc).
> > When you check for types (e.g. when displaying `Property`s in a GUI, the `[int]` form doesn't really work (you can work around it, but it's very hacky, and easier to go back to the source and fix it...)
> 
> So I checked, and it works with bad form as well unfortunately. I thought Python would raise an error as invalid type specification. Hopefully this change has got everything as the right types now, and we'll review types more closely going forward.

How about this: https://github.com/dstl/Stone-Soup/tree/type_hint_checking

This adds a few lines: 
```
+        for name, prop in cls._properties.items():
+            if not (isinstance(prop.cls, type) or
+                    str(prop.cls).startswith('typing.')):
+                raise ValueError(f'Invalid type specification ({str(prop.cls)}) '
+                                 f'for property {name} of class {cls.__name__}')
```

And also fixes the one case left in the codebase of an invalid type (`value: any = Property(doc='Value of the metric')` should be `value: typing.Any = Property(doc='Value of the metric')`. Good to see that it caught it though. If the idea is of use, I would add a test or two.

P.S. it uses f-strings, so needs to be added to this PR (if you like it), rather than making a new one

**Comment by sdhiscocks** [comment]
> > > Does this (or can it) disallow types of the form `[int]`, which is't actually a valid type (it is a list of types). It should be `List[int]` (or `Sequence[int]` etc).
> > > When you check for types (e.g. when displaying `Property`s in a GUI, the `[int]` form doesn't really work (you can work around it, but it's very hacky, and easier to go back to the source and fix it...)
> > 
> > 
> > So I checked, and it works with bad form as well unfortunately. I thought Python would raise an error as invalid type specification. Hopefully this change has got everything as the right types now, and we'll review types more closely going forward.
> 
> How about this: https://github.com/dstl/Stone-Soup/tree/type_hint_checking
> 
> This adds a few lines:
> 
> ```
> +        for name, prop in cls._properties.items():
> +            if not (isinstance(prop.cls, type) or
> +                    str(prop.cls).startswith('typing.')):
> +                raise ValueError(f'Invalid type specification ({str(prop.cls)}) '
> +                                 f'for property {name} of class {cls.__name__}')
> ```
> 
> And also fixes the one case left in the codebase of an invalid type (`value: any = Property(doc='Value of the metric')` should be `value: typing.Any = Property(doc='Value of the metric')`. Good to see that it caught it though. If the idea is of use, I would add a test or two.
> 
> P.S. it uses f-strings, so needs to be added to this PR (if you like it), rather than making a new one

Great. May as well get it in this PR as well if you wanna go ahead and fast-forward merge your branch onto this one.

**Comment by etfrogers-dstl** [comment]
Another thought: the current logic has the argument winning if both a type hint and argument are specified. 

Is that the right behaviour? Should we warn/raise an error/ignore/something else?

**Comment by etfrogers-dstl** [comment]
> Another thought: the current logic has the argument winning if both a type hint and argument are specified.
> 
> Is that the right behaviour? Should we warn/raise an error/ignore/something else?

Oh, and what if the type is NOT specified either way?

**Comment by etfrogers-dstl** [comment]
I also added checks that raise errors in both the following cases:
``` python
i: float = Property(int, doc='Test')  # type specified twice
i = Property(doc='Test')  # type not specified
```
Is this the behaviour we want? 

I can't think of a use case where either of the above would be useful. If you really don't want to specify the type, you can use `typing.Any`.

**Review by oharrald-Dstl — APPROVED** [review]

**Pull request merged**
